// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ5mUEoyFrWg8fqvoqMLzB0gmWX6htIzM',
    appId: '1:30782395733:web:ecef23d5c031668b7e0bdc',
    messagingSenderId: '30782395733',
    projectId: 'myauth-63858',
    authDomain: 'myauth-63858.firebaseapp.com',
    storageBucket: 'myauth-63858.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLR9jaLgvsOManrTzwe7P-rpXb_VOAz0o',
    appId: '1:30782395733:android:657b80dbbc2517cf7e0bdc',
    messagingSenderId: '30782395733',
    projectId: 'myauth-63858',
    storageBucket: 'myauth-63858.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNgz6MXy-cj0NYhHt39kf-icOBY8DcWHU',
    appId: '1:30782395733:ios:91c2d396d01d3f127e0bdc',
    messagingSenderId: '30782395733',
    projectId: 'myauth-63858',
    storageBucket: 'myauth-63858.appspot.com',
    iosBundleId: 'com.example.anotherOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNgz6MXy-cj0NYhHt39kf-icOBY8DcWHU',
    appId: '1:30782395733:ios:91c2d396d01d3f127e0bdc',
    messagingSenderId: '30782395733',
    projectId: 'myauth-63858',
    storageBucket: 'myauth-63858.appspot.com',
    iosBundleId: 'com.example.anotherOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ5mUEoyFrWg8fqvoqMLzB0gmWX6htIzM',
    appId: '1:30782395733:web:328997e2482f54ae7e0bdc',
    messagingSenderId: '30782395733',
    projectId: 'myauth-63858',
    authDomain: 'myauth-63858.firebaseapp.com',
    storageBucket: 'myauth-63858.appspot.com',
  );

}